project_tracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('tasks/', include('tasks.urls')),
    path('quality_control/', include('quality_control.urls')),
]

quality_control/urls.py
from django.urls import path
from quality_control import views

app_name = 'quality_control'

urlpatterns = [
    # path('', views.index, name='index'),
    path('', views.IndexView.as_view(), name='index'),
    path('bugs/', views.bug_list, name='bug_list'),
    path('bugs/', views.BugReportListView.as_view(), name='bug_list'),
    path('features/', views.feature_list, name='feature_list'),
    path('features/', views.FeatureRequestListView.as_view(), name='feature_list'),
    path('bugs/<int:bug_id>/', views.BugReportDetailView.as_view(), name='bug_detail'),
    path('bugs/<int:bug_id>/', views.bug_detail, name='bug_detail'),
    path('features/<int:feature_id>/', views.FeatureRequestDetailView.as_view(), name='feature_detail'),
    path('features/<int:feature_id>/', views.feature_detail, name='feature_detail'),
    path('bugs/new/', views.create_bug_report, name='create_bug_report'),
    path('bugs/create/', views.BugReportCreateView.as_view(), name='create_bug_report'),
    path('features/new/', views.create_feature_request, name='create_feature_request'),
    path('features/create/', views.FeatureRequestCreateView.as_view(), name='create_feature_request'),
    path('bugs/<int:bug_id>/update/', views.update_bug_report, name='update_bug'),
    path('features/<int:feature_id>/update/', views.update_feature_request, name='update_feature'),
    path('bugs/<int:bug_id>/update/', views.BugReportUpdateView.as_view(), name='update_bug'),
    path('features/<int:feature_id>/update/', views.FeatureRequestUpdateView.as_view(), name='update_feature'),
    path('bugs/<int:bug_id>/delete/', views.delete_bug, name='delete_bug'),
    path('features/<int:feature_id>/delete/', views.delete_feature, name='delete_feature'),
    path('bugs/<int:bug_id>/delete/', views.BugReportDeleteView.as_view(), name='delete_bug'),
    path('features/<int:feature_id>/delete/', views.FeatureRequestDeleteView.as_view(), name='delete_feature'),
]

tasks/urls.py
from django.urls import path
from tasks import views

app_name = 'tasks'

urlpatterns = [

    # path('', views.index),
    # path('projects/', views.projects_list, name='projects_list'),
    # path('projects/<int:project_id>/', views.project_detail, name='project_detail'),
    # path('projects/<int:project_id>/tasks/<int:task_id>/', views.task_detail, name='task_detail'),

    path('', views.IndexView.as_view(), name='index'),
    path('projects/', views.ProjectsListView.as_view(), name='projects_list'),
    path('projects/<int:project_id>/', views.ProjectDetailView.as_view(), name='project_detail'),
    path('projects/<int:project_id>/tasks/<int:task_id>/', views.TaskDetailView.as_view(), name='task_detail'),
    path('project/new/', views.create_project, name='create_project'),
    path('project/<int:project_id>/add_task/', views.add_task_to_project, name='add_task_to_project'),
    path('project/create/', views.ProjectCreateView.as_view(), name='create_project'),
    path('project/<int:project_id>/add_task/', views.TaskCreateView.as_view(), name='add_task_to_project'),
    path('project/<int:project_id>/update/', views.update_project, name='update_project'),
    path('project/<int:project_id>/task/<int:task_id>/update/', views.update_task, name='update_task'),
    path('project/<int:project_id>/update/', views.ProjectUpdateView.as_view(), name='update_project'),
    path('project/<int:project_id>/tasks/<int:task_id>/update/', views.TaskUpdateView.as_view(), name='update_task'),
    path('project/<int:project_id>/delete/', views.delete_project, name='delete_project'),
    path('project/<int:project_id>/tasks/<int:task_id>/delete/', views.delete_task, name='delete_task'),
    path('project/<int:project_id>/delete/', views.ProjectDeleteView.as_view(), name='delete_project'),
    path('project/<int:project_id>/tasks/<int:task_id>/delete/', views.TaskDeleteView.as_view(), name='delete_task'),
]

quality_control/models.py
from django.db import models
from tasks.models import Project, Task


class BugReport(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    project = models.ForeignKey(
        Project,
        on_delete=models.CASCADE
    )
    task = models.ForeignKey(
        Task,
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )
    STATUS_CHOICES = [
        ('New', 'Новая'),
        ('In_progress', 'В работе'),
        ('Completed', 'Завершена'),
    ]
    status = models.CharField(
        max_length=50,
        choices=STATUS_CHOICES,
        default='New',
    )
    PRIORITY_CHOICES = [
        ('1', '1'),
        ('2', '2'),
        ('3', '3'),
        ('4', '4'),
        ('5', '5'),
    ]
    priority = models.CharField(
        max_length=1,
        choices=PRIORITY_CHOICES,
        default='1',
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class FeatureRequest(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    project = models.ForeignKey(
        Project,
        on_delete=models.CASCADE
    )
    task = models.ForeignKey(
        Task,
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )
    STATUS_CHOICES = [
        ('Review', 'Рассмотрение'),
        ('Accepted', 'Принято'),
        ('Rejected', 'Отклонено'),
    ]
    status = models.CharField(
        max_length=50,
        choices=STATUS_CHOICES,
        default='Review',
    )
    PRIORITY_CHOICES = [
        ('1', '1'),
        ('2', '2'),
        ('3', '3'),
        ('4', '4'),
        ('5', '5'),
    ]
    priority = models.CharField(
        max_length=1,
        choices=PRIORITY_CHOICES,
        default='1',
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

quality_control/forms.py
from django import forms
from django.forms import ModelForm
from .models import BugReport, FeatureRequest


class BugReportForm(forms.ModelForm):
    class Meta:
        model = BugReport
        fields = ['title', 'description', 'status', 'priority', 'project', 'task']


class FeatureRequestForm(forms.ModelForm):
    class Meta:
        model = FeatureRequest
        fields = ['title', 'description', 'status', 'priority', 'project', 'task']

quality_control/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from .models import BugReport, FeatureRequest
from django.views import View
from django.views.generic import CreateView, DetailView, ListView, UpdateView, DeleteView
from .forms import BugReportForm, FeatureRequestForm
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy


class IndexView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'quality_control/index.html')


def bug_list(request):
    bugs = BugReport.objects.all()
    return render(request, 'quality_control/bug_list.html', {'bug_list': bugs})


class BugReportListView(ListView):
    model = BugReport
    template_name = 'quality_control/bug_list.html'


class BugReportDetailView(DetailView):
    model = BugReport
    pk_url_kwarg = 'bug_id'
    template_name = 'quality_control/bug_detail.html'


def bug_detail(request, bug_id):
    bug = get_object_or_404(BugReport, id=bug_id)
    return render(request, 'quality_control/bug_detail.html', {'bug': bug})


def feature_list(request):
    features = FeatureRequest.objects.all()
    return render(request, 'quality_control/feature_list.html', {'feature_list': features})


class FeatureRequestListView(ListView):
    model = FeatureRequest
    template_name = 'quality_control/feature_list.html'


class FeatureRequestDetailView(DetailView):
    model = FeatureRequest
    pk_url_kwarg = 'feature_id'
    template_name = 'quality_control/feature_detail.html'


def feature_detail(request, feature_id):
    feature = get_object_or_404(FeatureRequest, id=feature_id)
    return render(request, 'quality_control/feature_detail.html', {'feature': feature})


def create_bug_report(request):
    if request.method == 'POST':
        form = BugReportForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('quality_control:bug_list')
    else:
        form = BugReportForm()
    return render(request, 'quality_control/bug_report_form.html', {'form': form})


class BugReportCreateView(CreateView):
    model = BugReport
    form_class = BugReportForm
    template_name = 'quality_control/bug_report_form.html'
    success_url = reverse_lazy('quality_control:bug_list')


def create_feature_request(request):
    if request.method == 'POST':
        form = FeatureRequestForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('quality_control:feature_list')
    else:
        form = FeatureRequestForm()
    return render(request, 'quality_control/feature_request_form.html', {'form': form})


class FeatureRequestCreateView(CreateView):
    model = FeatureRequest
    form_class = FeatureRequestForm
    template_name = 'quality_control/feature_request_form.html'
    success_url = reverse_lazy('quality_control:feature_list')


def update_bug_report(request, bug_id):
    bug = get_object_or_404(BugReport, pk=bug_id)
    if request.method == 'POST':
        form = BugReportForm(request.POST, instance=bug)
        if form.is_valid():
            form.save()
            return redirect('quality_control:bug_detail', bug_id=bug.id)
    else:
        form = BugReportForm(instance=bug)
    return render(request, 'quality_control/bug_update.html', {'form': form, 'bug': bug})


class BugReportUpdateView(UpdateView):
    model = BugReport
    form_class = BugReportForm
    template_name = 'quality_control/bug_update.html'
    pk_url_kwarg = 'bug_id'
    success_url = reverse_lazy('quality_control:bug_list')


def update_feature_request(request, feature_id):
    feature = get_object_or_404(FeatureRequest, pk=feature_id)
    if request.method == 'POST':
        form = FeatureRequestForm(request.POST, instance=feature)
        if form.is_valid():
            form.save()
            return redirect('quality_control:feature_detail', feature_id=feature.id)
    else:
        form = FeatureRequestForm(instance=feature)
    return render(request, 'quality_control/feature_update.html', {'form': form, 'feature': feature})


class FeatureRequestUpdateView(UpdateView):
    model = FeatureRequest
    form_class = FeatureRequestForm
    template_name = 'quality_control/feature_update.html'
    pk_url_kwarg = 'feature_id'
    success_url = reverse_lazy('quality_control:feature_list')


def delete_bug(request, bug_id):
    bug = get_object_or_404(BugReport, pk=bug_id)
    bug.delete()
    return redirect('quality_control:bug_list')


class BugReportDeleteView(DeleteView):
    model = BugReport
    pk_url_kwarg = 'bug_id'
    success_url = reverse_lazy('quality_control:bug_list')
    template_name = 'quality_control/bug_confirm_delete.html'


def delete_feature(request, feature_id):
    feature = get_object_or_404(FeatureRequest, pk=feature_id)
    feature.delete()
    return redirect('quality_control:feature_list')


class FeatureRequestDeleteView(DeleteView):
    model = FeatureRequest
    pk_url_kwarg = 'feature_id'
    success_url = reverse_lazy('quality_control:feature_list')
    template_name = 'tasks/feature_confirm_delete.html'

# def index(request):
#     bug_list_url = reverse('quality_control:bug_list')
#     feature_list_url = reverse('quality_control:feature_list')
#     html = f"<h1>Система контроля качества</h1><a href='{bug_list_url}'>Список всех багов</a></br><a href='{feature_list_url}'>Список всех запросов на улучшение</a>"
#     return HttpResponse(html)

# class IndexView(View):
#     def get(self, request, *args, **kwargs):
#         bug_list_url = reverse('quality_control:bug_list')
#         feature_list_url = reverse('quality_control:feature_list')
#         html = f"<h1>Система контроля качества</h1><a href='{bug_list_url}'>Список всех багов</a></br><a href='{feature_list_url}'>Список всех запросов на улучшение</a>"
#         return HttpResponse(html)

# def bug_list(request):
#     bugs = BugReport.objects.all()
#     bugs_html = '<h1>Cписок отчетов об ошибках</h1><ul>'
#     for bug in bugs:
#         bugs_html += f'<li><a href="{bug.id}/">{bug.title}</a><a> - {bug.status}</a></li>'
#     bugs_html += '</ul>'
#     return HttpResponse(bugs_html)


# class BugReportDetailView(DetailView):
#     model = BugReport
#     pk_url_kwarg = 'bug_id'
#
#     def get(self, request, *args, **kwargs):
#         self.object = self.get_object()
#         bug = self.object
#         task = bug.task
#         project = bug.project
#         project_list_url = reverse('tasks:projects_list')
#         tasks_list_url = reverse('tasks:index')
#         response_html = f'<h1>{bug.title}</h1><p>Description: {bug.description}</p><p>Status: {bug.status}</p><p>Priority: {bug.priority}</p>'
#         response_html += '<h2>Проект</h2><ul>'
#         response_html += f'<li><a href="{project_list_url}{project.id}/">{project.name}</a></li>'
#         response_html += '</ul>'
#         response_html += '<h2>Задача</h2><ul>'
#         response_html += f'<li><a href="{project_list_url}{project.id}{tasks_list_url}{task.id}/">{task.name}</a></li>'
#         response_html += '</ul>'
#         return HttpResponse(response_html)


# def feature_list(request):
#     features = FeatureRequest.objects.all()
#     features_html = '<h1>Список запросов на улучшение</h1><ul>'
#     for feature in features:
#         features_html += f'<li><a href="{feature.id}/">{feature.title}</a><a> - {feature.status}</a></li>'
#     features_html += '</ul>'
#     return HttpResponse(features_html)


# class FeatureRequestDetailView(DetailView):
#     model = FeatureRequest
#     pk_url_kwarg = 'feature_id'
#
#     def get(self, request, *args, **kwargs):
#         self.object = self.get_object()
#         feature = self.object
#         task = feature.task
#         project = feature.project
#         project_list_url = reverse('tasks:projects_list')
#         tasks_list_url = reverse('tasks:index')
#         response_html = f'<h1>{feature.title}</h1><p>Description: {feature.description}</p><p>Status: {feature.status}</p><p>Priority: {feature.priority}</p>'
#         response_html += '<h2>Проект</h2><ul>'
#         response_html += f'<li><a href="{project_list_url}{project.id}/">{project.name}</a></li>'
#         response_html += '</ul>'
#         response_html += '<h2>Задача</h2><ul>'
#         response_html += f'<li><a href="{project_list_url}{project.id}{tasks_list_url}{task.id}/">{task.name}</a></li>'
#         response_html += '</ul>'
#         return HttpResponse(response_html)

quality_control/templates/quality_control/bug_confirm_delete.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Удаление отчёта об ошибке</h1>
    <p>Вы уверены, что хотите удалить отчёт об ошибке "{{ bug.title }}"?</p>

    <form action="{% url 'quality_control:delete_bug' bug.id %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Удалить">
        <a href="{% url 'quality_control:bug_detail' bug.id %}">Отмена</a>
    </form>
{% endblock %}

quality_control/templates/quality_control/bug_detail.html
{% extends 'base/base.html' %}

{% block content %}
    <h3>{{ bugreport.title }}</h3>
    <p><a href="{% url 'quality_control:update_bug' bugreport.id %}">Изменить отчёт об ошибке</a></p>
    <p><a href="{% url 'quality_control:delete_bug' bugreport.id %}"onclick="return confirm('Вы уверены, что хотите удалить этот отчёт об ошибке?');">Удалить отчёт об ошибке</a></p>
    <ul>
        <li><b>Описание:</b> {{ bugreport.description }}</li>
        <li><b>Статус:</b> {{ bugreport.status }}</li>
        <li><b>Приоритет:</b> {{ bugreport.priority }}</li>
        <li><b>Проект: </b><a href="{% url 'tasks:project_detail' bugreport.project.id %}">{{ bugreport.project }}</a></li>
        {% if featurerequest.task.id %}
            <li><b>Задача: </b><a href="{% url 'tasks:task_detail' bugreport.project.id bugreport.task.id %}">{{ bugreport.task }}</a></li>
        {% else %}
            <li><b>Задача: </b>-</li>
        {% endif %}
    </ul>
{% endblock %}

quality_control/templates/quality_control/bug_list.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Cписок отчетов об ошибках</h1>

    <p><a href="{% url 'quality_control:create_bug_report' %}">Создать новый отчёт об ошибке</a></p>

    <ul>
        {% for bug in bug_list %}
            <li><a href="{% url 'quality_control:bug_detail' bug.id %}">{{ bug.title }}</a>: {{ bug.status }}</li>
        {% endfor %}
    </ul>
{% endblock %}

quality_control/templates/quality_control/bug_report_form.html
{% extends 'base/base.html' %}

{% block content %}
<h2>Создать новый отчёт об ошибке</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить</button>
    </form>
{% endblock %}

quality_control/templates/quality_control/bug_update.html
{% extends 'base/base.html' %}

{% block content %}
<h2>Изменение отчёта об ошибке: {{ bugreport.name }}</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить</button>
    </form>
{% endblock %}

quality_control/templates/quality_control/feature_confirm_delete.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Удаление запроса на улучшение</h1>
    <p>Вы уверены, что хотите удалить запрос на улучшение "{{ feature.title }}"?</p>

    <form action="{% url 'quality_control:delete_feature' feature.id %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Удалить">
        <a href="{% url 'quality_control:feature_detail' feature.id %}">Отмена</a>
    </form>
{% endblock %}

quality_control/templates/quality_control/feature_detail.html
{% extends 'base/base.html' %}

{% block content %}
    <h3>{{ featurerequest.title }}</h3>
    <p><a href="{% url 'quality_control:update_feature' featurerequest.id %}">Изменить запрос на улучшение</a></p>
    <p><a href="{% url 'quality_control:delete_feature' featurerequest.id %}"onclick="return confirm('Вы уверены, что хотите удалить этот запрос на улучшение?');">Удалить запрос на улучшение</a></p>
    <ul>
        <li><b>Описание:</b> {{ featurerequest.description }}</li>
        <li><b>Статус:</b> {{ featurerequest.status }}</li>
        <li><b>Приоритет:</b> {{ featurerequest.priority }}</li>
        <li><b>Проект: </b><a href="{% url 'tasks:project_detail' featurerequest.project.id %}">{{ featurerequest.project }}</a></li>
        {% if featurerequest.task.id %}
            <li><b>Задача: </b><a href="{% url 'tasks:task_detail' featurerequest.project.id featurerequest.task.id %}">{{ featurerequest.task }}</a></li>
        {% else %}
            <li><b>Задача: </b>-</li>
        {% endif %}
    </ul>

{% endblock %}

quality_control/templates/quality_control/feature_list.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Список запросов на улучшение</h1>

    <p><a href="{% url 'quality_control:create_feature_request' %}">Создать новый запрос на улучшение</a></p>

    <ul>
        {% for feature in feature_list %}
            <li><a href="{% url 'quality_control:feature_detail' feature.id %}">{{ feature.title }}</a>: {{ feature.status }}</li>
        {% endfor %}
    </ul>
{% endblock %}

quality_control/templates/quality_control/feature_request_form.html
{% extends 'base/base.html' %}

{% block content %}
<h2>Создать новый запрос на улучшение</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить</button>
    </form>
{% endblock %}

quality_control/templates/quality_control/feature_update.html
{% extends 'base/base.html' %}

{% block content %}
<h2>Изменение запроса на улучшение: {{ feature.name }}</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить</button>
    </form>
{% endblock %}

quality_control/templates/quality_control/index.html
{% extends 'base/base.html' %}

{% block content %}
        <h1>Система контроля качества</h1>
        <a href="{% url 'quality_control:bug_list' %}">Список всех багов</a><br>
        <a href="{% url 'quality_control:feature_list' %}">Список всех запросов на улучшение</a>
{% endblock %}